language: python

cache: pip

matrix:
  include:
    - name: "Python 3.7"
      python: 3.7
      dist: xenial

services:
  - mysql
  - postgresql

install:
  - pip install "." .

script: python3 -m pytest tests -rs
